export type ListingType = "apartment" | "house" | "land" | "commercial";
export type DealKind = "sale" | "rent";
export type ListingStatus = "draft" | "active" | "sold" | "archived";
export type OwnerKind = "private" | "agency";

export interface Multilingual {
  en: string;
  me: string;
  ru: string;
}

export interface Agency {
  id: string;
  slug: string;
  name: string;
  logo: string;     // emoji for now; URL later
  color: string;    // brand accent
  phone: string;
  email: string;
  website: string;
  description: Multilingual;
  listingsCount: number;
  verified: boolean;
}

export interface Location {
  city: string;
  neighborhood?: string;
  lat: number;
  lng: number;
  address?: string;
}

export interface Listing {
  id: string;
  ownerKind: OwnerKind;
  agencyId: string | null;       // null when ownerKind === "private"
  ownerName?: string;             // private seller name
  type: ListingType;
  deal: DealKind;
  status: ListingStatus;
  title: Multilingual;
  description: Multilingual;
  price: number;                  // EUR (rent: per month)
  area: number;                   // m²
  beds: number;
  baths: number;
  yearBuilt?: number;
  features: string[];             // free tags ("sea view", "parking", "balcony")
  location: Location;
  image: string;                  // hero image URL
  images: string[];               // gallery
  featured: boolean;
  createdAt: string;              // ISO
}

export interface BuyerProfile {
  id: string;
  userId: string;
  deal: DealKind | "any";
  types: ListingType[];           // empty = any
  cities: string[];               // empty = any
  budgetMin?: number;
  budgetMax?: number;
  bedsMin?: number;
  areaMin?: number;
  freeText: string;               // user's own description of what they want
  mustHaves: string[];            // hard constraints from extracted features
  niceToHaves: string[];          // soft preferences
  updatedAt: string;
}

export interface MatchResult {
  listing: Listing;
  score: number;                  // 0..1
  why: string;                    // 1-line explanation generated by Claude
}

export interface Inquiry {
  id: string;
  listingId: string;
  fromUserId: string;
  toAgencyId: string | null;
  toUserId: string | null;
  message: string;
  createdAt: string;
}
